print("print(")

for i in ["H", "e", "l", "l", "o", ","," ", "W", "o", "r", "l", "d", "!"]:
    print("chr(")
    for j in range(0, ord(i)):
        if j == ord(i)-1:
            print("len([[]])", end="")
        else:
            print("len([[]])+", end="")
    if i == "!":
        print("))")
    else:
        print(")+")

print(
chr(
len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]]))+
chr(
len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]]))+
chr(
len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]]))+
chr(
len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]]))+
chr(
len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]]))+
chr(
len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]]))+   
chr(
len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]]))+
chr(
len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]]))+
chr(
len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]]))+
chr(
len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]]))+
chr(
len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]]))+
chr(
len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]]))+
chr(
len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])+len([[]])))
